#!/usr/bin/env bash
# pergamino-start — install.sh
# Sets up the two pergaminos in your home directory.
#
# Usage:  ./install.sh
# Idempotent: re-running it is safe; existing folders are left untouched.

set -euo pipefail

# Colors for readability (with fallback if stdout isn't a tty)
if [ -t 1 ]; then
  RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; CYAN=$'\033[36m'; BOLD=$'\033[1m'; RESET=$'\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; CYAN=''; BOLD=''; RESET=''
fi

PERGAMINO_HOME="${PERGAMINO_HOME:-$HOME}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAIN_VAULT="$PERGAMINO_HOME/MainVault"
LLM_VAULT="$PERGAMINO_HOME/LLMVault"

echo ""
echo "${BOLD}Installing Pergamino${RESET}"
echo "${CYAN}— two scrolls, one author, one librarian —${RESET}"
echo ""

# ──────────────────────────────────────────────────────
# 1. Create MainVault — the author's brain
# ──────────────────────────────────────────────────────

if [ -d "$MAIN_VAULT" ]; then
  echo "${YELLOW}⏭${RESET}  $MAIN_VAULT already exists — leaving untouched."
else
  mkdir -p "$MAIN_VAULT"/{beliefs,principles,life-decisions,heartbeats}
  echo "${GREEN}✓${RESET}  Created ${BOLD}$MAIN_VAULT${RESET}"
  echo "      └─ beliefs/  principles/  life-decisions/  heartbeats/"
fi

# Drop a starter belief if MainVault was empty
if [ ! -f "$MAIN_VAULT/beliefs/why-pergamino.md" ] && [ ! -f "$MAIN_VAULT/.installed" ]; then
  cp "$SCRIPT_DIR/templates/main-vault-starter.md" "$MAIN_VAULT/beliefs/why-pergamino.md" 2>/dev/null || true
  touch "$MAIN_VAULT/.installed"
fi

# ──────────────────────────────────────────────────────
# 2. Create LLMVault — the librarian's brain
# ──────────────────────────────────────────────────────

if [ -d "$LLM_VAULT" ]; then
  echo "${YELLOW}⏭${RESET}  $LLM_VAULT already exists — leaving untouched."
else
  mkdir -p "$LLM_VAULT"/{raw/articles,raw/web,raw/papers,wiki/concepts,wiki/themes,wiki/projects,wiki/summaries,wiki/syntheses,outputs/mainvault-pending}
  echo "${GREEN}✓${RESET}  Created ${BOLD}$LLM_VAULT${RESET}"
  echo "      ├─ raw/        (immutable sources — articles/, papers/, web/)"
  echo "      ├─ wiki/       (the catalog — concepts/, themes/, summaries/)"
  echo "      └─ outputs/mainvault-pending/  (the tray — proposals back to you)"
fi

# Initialize the index and log
[ -f "$LLM_VAULT/wiki/_index.md" ] || cat > "$LLM_VAULT/wiki/_index.md" <<EOF
---
type: index
title: Pergamino Index
generated: $(date +%Y-%m-%d)
---

# Pergamino — Index

This file is regenerated by the librarian as the catalog grows.

## Sections

- [Concepts](./concepts/) — frameworks, mental models, ideas you track
- [Themes](./themes/) — topics you're researching across many sources
- [Projects](./projects/) — active work and decisions
- [Summaries](./summaries/) — one per source you've ingested
- [Syntheses](./syntheses/) — your own writing, drawn from the catalog

EOF

[ -f "$LLM_VAULT/wiki/log.md" ] || cat > "$LLM_VAULT/wiki/log.md" <<EOF
---
type: log
---

# Pergamino — Log

Append-only chronicle of what the librarian has done. One entry per ingest, query, lint, or maintain operation.

EOF

# ──────────────────────────────────────────────────────
# 3. Confirm the rules folder is in place
# ──────────────────────────────────────────────────────

for f in AGENTS.md CLAUDE.md RESOLVER.md prompt-for-llm.md; do
  if [ ! -f "$SCRIPT_DIR/$f" ]; then
    echo "${RED}✗${RESET}  Missing $SCRIPT_DIR/$f — your install is incomplete."
    exit 1
  fi
done
echo "${GREEN}✓${RESET}  Rules folder present (AGENTS.md, CLAUDE.md, RESOLVER.md)"

# ──────────────────────────────────────────────────────
# 4. Detect available LLMs
# ──────────────────────────────────────────────────────

LLM_FOUND=""
for cmd in claude codex gpt gemini aider; do
  if command -v "$cmd" >/dev/null 2>&1; then
    LLM_FOUND="$cmd"
    break
  fi
done

# ──────────────────────────────────────────────────────
# 5. Done — print next steps
# ──────────────────────────────────────────────────────

echo ""
echo "${BOLD}🎉  Pergamino installed.${RESET}"
echo ""
echo "${BOLD}Next:${RESET}"
echo "    1. ${CYAN}cd $SCRIPT_DIR${RESET}"
if [ -n "$LLM_FOUND" ]; then
  echo "    2. ${CYAN}$LLM_FOUND${RESET}    ${YELLOW}# detected on your system${RESET}"
else
  echo "    2. ${CYAN}claude${RESET}        ${YELLOW}# or 'codex', 'gemini', 'aider', or any CLI LLM${RESET}"
fi
echo "    3. Paste the contents of ${CYAN}prompt-for-llm.md${RESET} into your first message."
echo ""
echo "${BOLD}Your first inscription:${RESET}"
echo "    Open ${CYAN}$MAIN_VAULT/beliefs/why-pergamino.md${RESET}"
echo "    and write three sentences in your own voice. Why are you doing this?"
echo ""
echo "${CYAN}— pergamino.ai${RESET}"
echo ""
